### ISSUE TITLE
[BUG] failed to run cmake?

### ISSUE THREAD

**Issue by eunju6460** [ElectroGamesDev/Cryonic-Engine#1]
**Describe the bug**
if click "play" or "build project" 
Not running properly

**To Reproduce**
click "play" or "build project" 
Not running properly
see console 
log  = build - failed to run cmake
installed cmake but same error

**Expected behavior**

**Screenshots**
<img width="416" alt="error" src="https://github.com/user-attachments/assets/2d272736-9780-40a3-8feb-ee866546a1de">

**Additional context**

**Comment by ElectroGamesDev** [comment]
The cmake function actually also uses MinGW32 so you will need to have this installed. You can install it using this install manager: https://sourceforge.net/projects/mingw/

I will add some checks to see if both cmake and MinGW32 are installed so I can send proper errors.

I've never tested the build system or game engine on other systems, so I wouldn't be surprised if it has some issues.
For the v0.1 beta release, I do plan to test everything on other systems as well as include MinGW32 and Cmake in the installation.

The game engine is missing documentation, a lot of 3D features, and has some bugs. If you come across any issues or missing features you would like to see, feel free to open up an issue!

**Comment by eunju6460** [comment]
fix it thanks
